remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Curso aberto - REA e licenças Creative Commons]
description: [Um curso autoinstrucional sobre Recursos Educacionais Abertos e licenças de uso]
